# filename: product/schemas/user_schema.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import re

from pydantic import (
    AliasChoices,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
)


class UserCreate(BaseModel):
    name: str = Field(
        ...,
        min_length=1,
        max_length=50,
    )

    email: EmailStr

    password: str = Field(
        ...,
        min_length=8,
        max_length=128,
    )

    mobile: str = Field(
        ...,
        min_length=10,
        max_length=15,
        description="Enter 10 to 15 numbers only.",
        examples=["9876543210"],
    )

    @field_validator("mobile")
    @classmethod
    def validate_mobile(cls, value: str) -> str:
        mobile = value.strip()

        if not re.fullmatch(r"[0-9]{10,15}", mobile):
            raise ValueError(
                "Type numbers only. Mobile must contain 10 to 15 digits.",
            )

        return mobile


class UserResponse(BaseModel):
    user_id: int = Field(
        validation_alias=AliasChoices(
            "user_id",
            "UserID",
        ),
    )

    name: str = Field(
        validation_alias=AliasChoices(
            "name",
            "Name",
        ),
    )

    email: EmailStr = Field(
        validation_alias=AliasChoices(
            "email",
            "Email",
        ),
    )

    mobile: str = Field(
        validation_alias=AliasChoices(
            "mobile",
            "Mobile",
        ),
    )

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True,
    )


class UserLogin(BaseModel):
    email: EmailStr

    password: str = Field(
        ...,
        min_length=8,
    )


class LoginResponse(BaseModel):
    message: str
    user_id: int
    name: str
    email: EmailStr


class TokenResponse(BaseModel):
    access_token: str
    token_type: str
