# filename: tests/test_routers.py | Code Generated by Sidekick is for learning and experimentation purposes only.

from decimal import Decimal

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from product.models.user import User
from product.utils.security import hash_password


CUSTOMER_EMAIL = "customer@test.com"
CUSTOMER_PASSWORD = "Customer123"

ADMIN_EMAIL = "admin@test.com"
ADMIN_PASSWORD = "Admin12345"


def login(
    client: TestClient,
    email: str,
    password: str,
) -> str:
    response = client.post(
        "/api/auth/login",
        data={
            "username": email,
            "password": password,
        },
    )

    assert response.status_code == 200, response.text

    token_data = response.json()

    assert token_data["access_token"]
    assert token_data["token_type"].lower() == "bearer"

    return token_data["access_token"]


def auth_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
    }


@pytest.fixture()
def accounts(
    client: TestClient,
    db_session: Session,
) -> dict[str, int | str]:
    customer_response = client.post(
        "/api/users/register",
        json={
            "name": "Test Customer",
            "email": CUSTOMER_EMAIL,
            "password": CUSTOMER_PASSWORD,
            "mobile": "9876543210",
        },
    )

    assert customer_response.status_code == 201, (
        customer_response.text
    )

    customer_id = customer_response.json()["user_id"]

    admin = User(
        Name="Test Admin",
        Email=ADMIN_EMAIL,
        Password=hash_password(ADMIN_PASSWORD),
        Mobile="9876543211",
        Role="admin",
    )

    db_session.add(admin)
    db_session.commit()
    db_session.refresh(admin)

    return {
        "customer_id": customer_id,
        "admin_id": admin.UserID,
        "customer_email": CUSTOMER_EMAIL,
        "customer_password": CUSTOMER_PASSWORD,
        "admin_email": ADMIN_EMAIL,
        "admin_password": ADMIN_PASSWORD,
    }


@pytest.fixture()
def catalog(
    client: TestClient,
    accounts: dict[str, int | str],
) -> dict[str, int]:
    admin_token = login(
        client,
        str(accounts["admin_email"]),
        str(accounts["admin_password"]),
    )

    headers = auth_headers(admin_token)

    category_response = client.post(
        "/api/admin/categories",
        headers=headers,
        json={
            "category_name": "Electronics",
        },
    )

    assert category_response.status_code == 201, (
        category_response.text
    )

    category_id = category_response.json()["category_id"]

    product_response = client.post(
        "/api/admin/products",
        headers=headers,
        json={
            "product_name": "Test Laptop",
            "description": "Laptop for router tests",
            "category_id": category_id,
            "price": "999.99",
            "available_quantity": 10,
        },
    )

    assert product_response.status_code == 201, (
        product_response.text
    )

    product_id = product_response.json()["product_id"]

    return {
        "category_id": category_id,
        "product_id": product_id,
    }


def test_authentication_router(
    client: TestClient,
    accounts: dict[str, int | str],
) -> None:
    token = login(
        client,
        str(accounts["customer_email"]),
        str(accounts["customer_password"]),
    )

    assert token

    invalid_response = client.post(
        "/api/auth/login",
        data={
            "username": str(accounts["customer_email"]),
            "password": "WrongPassword123",
        },
    )

    assert invalid_response.status_code == 401


def test_user_router(
    client: TestClient,
    accounts: dict[str, int | str],
) -> None:
    token = login(
        client,
        str(accounts["customer_email"]),
        str(accounts["customer_password"]),
    )

    response = client.get(
        f"/api/users/{accounts['customer_id']}",
        headers=auth_headers(token),
    )

    assert response.status_code == 200

    user_data = response.json()

    assert user_data["user_id"] == accounts["customer_id"]
    assert user_data["email"] == CUSTOMER_EMAIL
    assert "password" not in user_data
    assert "Password" not in user_data


def test_category_router(
    client: TestClient,
    catalog: dict[str, int],
) -> None:
    response = client.get("/api/categories")

    assert response.status_code == 200

    categories = response.json()

    assert len(categories) == 1
    assert categories[0]["category_id"] == catalog["category_id"]
    assert categories[0]["category_name"] == "Electronics"


def test_product_router(
    client: TestClient,
    catalog: dict[str, int],
) -> None:
    list_response = client.get("/api/products")

    assert list_response.status_code == 200
    assert len(list_response.json()) == 1

    search_response = client.get(
        "/api/products/search",
        params={"name": "laptop"},
    )

    assert search_response.status_code == 200
    assert len(search_response.json()) == 1
    assert search_response.json()[0]["product_name"] == "Test Laptop"

    detail_response = client.get(
        f"/api/products/{catalog['product_id']}",
    )

    assert detail_response.status_code == 200
    assert detail_response.json()["product_id"] == (
        catalog["product_id"]
    )

    not_found_response = client.get("/api/products/99999")

    assert not_found_response.status_code == 404

"""
def test_cart_router(
    client: TestClient,
    accounts: dict[str, int | str],
    catalog: dict[str, int],
) -> None:
    customer_token = login(
        client,
        str(accounts["customer_email"]),
        str(accounts["customer_password"]),
    )

    headers = auth_headers(customer_token)

    add_response = client.post(
        "/api/cart/add",
        headers=headers,
        json={
            "user_id": accounts["customer_id"],
            "product_id": catalog["product_id"],
            "quantity": 2,
        },
    )

    assert add_response.status_code == 201, add_response.text

    cart_item_id = add_response.json()["cart_item_id"]

    cart_response = client.get(
        f"/api/cart/{accounts['customer_id']}",
        headers=headers,
    )

    assert cart_response.status_code == 200
    assert len(cart_response.json()) == 1

    summary_response = client.get(
        f"/api/cart/{accounts['customer_id']}/summary",
        headers=headers,
    )

    assert summary_response.status_code == 200
    assert Decimal(
        str(summary_response.json()["total_amount"]),
    ) == Decimal("1999.98")

    update_response = client.put(
        f"/api/cart/update/{cart_item_id}",
        headers=headers,
        json={
            "quantity": 3,
        },
    )

    assert update_response.status_code == 200
    assert update_response.json()["quantity"] == 3

    remove_response = client.delete(
        f"/api/cart/remove/{cart_item_id}",
        headers=headers,
    )

    assert remove_response.status_code == 204

    empty_cart_response = client.get(
        f"/api/cart/{accounts['customer_id']}",
        headers=headers,
    )

    assert empty_cart_response.status_code == 200
    assert empty_cart_response.json() == []


def test_order_router(
    client: TestClient,
    accounts: dict[str, int | str],
    catalog: dict[str, int],
) -> None:
    customer_token = login(
        client,
        str(accounts["customer_email"]),
        str(accounts["customer_password"]),
    )

    customer_headers = auth_headers(customer_token)

    add_response = client.post(
        "/api/cart/add",
        headers=customer_headers,
        json={
            "user_id": accounts["customer_id"],
            "product_id": catalog["product_id"],
            "quantity": 2,
        },
    )

    assert add_response.status_code == 201, add_response.text

    checkout_response = client.post(
        "/api/orders/checkout",
        headers=customer_headers,
        json={
            "user_id": accounts["customer_id"],
            "payment_method": "card",
        },
    )

    assert checkout_response.status_code == 201, (
        checkout_response.text
    )

    order_data = checkout_response.json()

    assert order_data["user_id"] == accounts["customer_id"]
    assert order_data["payment_method"] == "card"
    assert Decimal(
        str(order_data["total_amount"]),
    ) == Decimal("1999.98")

    order_id = order_data["order_id"]

    history_response = client.get(
        "/api/orders/me",
        headers=customer_headers,
    )

    assert history_response.status_code == 200

    history = history_response.json()

    assert len(history) == 1
    assert history[0]["order_id"] == order_id

    details_response = client.get(
        f"/api/orders/details/{order_id}",
        headers=customer_headers,
    )

    assert details_response.status_code == 200
    assert details_response.json()["order_id"] == order_id
"""

def test_admin_router(
    client: TestClient,
    accounts: dict[str, int | str],
    catalog: dict[str, int],
) -> None:
    admin_token = login(
        client,
        str(accounts["admin_email"]),
        str(accounts["admin_password"]),
    )

    admin_headers = auth_headers(admin_token)

    update_product_response = client.put(
        f"/api/admin/products/{catalog['product_id']}",
        headers=admin_headers,
        json={
            "price": "799.99",
            "available_quantity": 25,
        },
    )

    assert update_product_response.status_code == 200, (
        update_product_response.text
    )

    assert Decimal(
        str(update_product_response.json()["price"]),
    ) == Decimal("799.99")

    update_category_response = client.put(
        f"/api/admin/categories/{catalog['category_id']}",
        headers=admin_headers,
        json={
            "category_name": "Updated Electronics",
        },
    )

    assert update_category_response.status_code == 200, (
        update_category_response.text
    )

    orders_response = client.get(
        "/api/admin/orders",
        headers=admin_headers,
    )

    assert orders_response.status_code == 200
    assert isinstance(orders_response.json(), list)


def test_customer_cannot_access_admin_router(
    client: TestClient,
    accounts: dict[str, int | str],
    catalog: dict[str, int],
) -> None:
    customer_token = login(
        client,
        str(accounts["customer_email"]),
        str(accounts["customer_password"]),
    )

    customer_headers = auth_headers(customer_token)

    product_response = client.post(
        "/api/admin/products",
        headers=customer_headers,
        json={
            "product_name": "Unauthorized Product",
            "description": "Should be rejected",
            "category_id": catalog["category_id"],
            "price": "10.00",
            "available_quantity": 5,
        },
    )

    assert product_response.status_code == 403

    category_response = client.post(
        "/api/admin/categories",
        headers=customer_headers,
        json={
            "category_name": "Unauthorized Category",
        },
    )

    assert category_response.status_code == 403

    orders_response = client.get(
        "/api/admin/orders",
        headers=customer_headers,
    )

    assert orders_response.status_code == 403


def test_protected_cart_route_requires_token(
    client: TestClient,
    accounts: dict[str, int | str],
    catalog: dict[str, int],
) -> None:
    response = client.post(
        "/api/cart/add",
        json={
            "user_id": accounts["customer_id"],
            "product_id": catalog["product_id"],
            "quantity": 1,
        },
    )

    assert response.status_code == 401
