# Code Generated by Sidekick is for learning and experimentation purposes only. | filename: tests/test_user.py

from fastapi.testclient import TestClient


USER_PAYLOAD = {
    "name": "Test Customer",
    "email": "customer@example.com",
    "password": "Password123",
    "mobile": "9876543210",
}


def test_register_user(client: TestClient) -> None:
    response = client.post(
        "/api/users/register",
        json=USER_PAYLOAD,
    )

    assert response.status_code == 201

    user_data = response.json()

    assert user_data["name"] == "Test Customer"
    assert user_data["email"] == "customer@example.com"
    assert user_data["mobile"] == "9876543210"
    assert "password" not in user_data
    assert "Password" not in user_data


def test_duplicate_email_rejected(client: TestClient) -> None:
    first_response = client.post(
        "/api/users/register",
        json=USER_PAYLOAD,
    )

    duplicate_response = client.post(
        "/api/users/register",
        json=USER_PAYLOAD,
    )

    assert first_response.status_code == 201
    assert duplicate_response.status_code in {400, 409}


def test_invalid_email_rejected(client: TestClient) -> None:
    invalid_payload = {
        **USER_PAYLOAD,
        "email": "invalid-email",
    }

    response = client.post(
        "/api/users/register",
        json=invalid_payload,
    )

    assert response.status_code == 422


def test_login_returns_access_token(client: TestClient) -> None:
    register_response = client.post(
        "/api/users/register",
        json=USER_PAYLOAD,
    )

    assert register_response.status_code == 201

    login_response = client.post(
        "/api/auth/login",
        data={
            "username": USER_PAYLOAD["email"],
            "password": USER_PAYLOAD["password"],
        },
    )

    assert login_response.status_code == 200

    token_data = login_response.json()

    assert token_data["access_token"]
    assert token_data["token_type"].lower() == "bearer"


def test_invalid_login_rejected(client: TestClient) -> None:
    response = client.post(
        "/api/auth/login",
        data={
            "username": USER_PAYLOAD["email"],
            "password": "WrongPassword123",
        },
    )

    assert response.status_code == 401
