# Code Generated by Sidekick is for learning and experimentation purposes only. | filename: tests/test_product.py

from decimal import Decimal

import pytest
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from product.schemas.product_schema import ProductCreate
from product.services import product_service


def test_list_products(
    client: TestClient,
    sample_catalog: tuple,
) -> None:
    response = client.get("/api/products")

    assert response.status_code == 200

    products = response.json()

    assert len(products) == 1
    assert products[0]["product_name"] == "Laptop"
    assert products[0]["available_quantity"] == 10


def test_get_product_by_id(
    client: TestClient,
    sample_catalog: tuple,
) -> None:
    _, product = sample_catalog

    response = client.get(f"/api/products/{product.ProductID}")

    assert response.status_code == 200

    product_data = response.json()

    assert product_data["product_id"] == product.ProductID
    assert product_data["product_name"] == "Laptop"
    assert product_data["price"] == "999.99"


def test_search_products(
    client: TestClient,
    sample_catalog: tuple,
) -> None:
    response = client.get(
        "/api/products/search",
        params={"name": "lap"},
    )

    assert response.status_code == 200

    products = response.json()

    assert len(products) == 1
    assert products[0]["product_name"] == "Laptop"


def test_product_not_found(client: TestClient) -> None:
    response = client.get("/api/products/99999")

    assert response.status_code == 404
    assert response.json()["detail"] == "Product not found"


def test_duplicate_product_name_rejected(
    db_session: Session,
    sample_catalog: tuple,
) -> None:
    product_data = ProductCreate(
        product_name="Laptop",
        description="Duplicate laptop",
        category_id=sample_catalog[0].CategoryID,
        price=Decimal("500.00"),
        available_quantity=5,
    )

    with pytest.raises(ValueError, match="already exists"):
        product_service.create_product(
            db=db_session,
            product_data=product_data,
        )
