# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: product/services/user_service.py
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from product.models.user import User
from product.repositories import user_repository
from product.schemas.user_schema import UserCreate, UserLogin
from product.utils.security import hash_password, verify_password


def create_user(db: Session, user_data: UserCreate) -> User:
    email = str(user_data.email).strip().lower()

    existing_user = user_repository.get_user_by_email(db, email)

    if existing_user is not None:
        raise ValueError("Email already exists")

    user = User(
        Name=user_data.name.strip(),
        Email=email,
        Password=hash_password(user_data.password),
        Mobile=user_data.mobile.strip(),
        Role="customer",
    )

    try:
        return user_repository.create_user(db, user)
    except IntegrityError as error:
        db.rollback()
        raise ValueError("Email already exists") from error


def get_user_by_id(
    db: Session,
    user_id: int,
) -> User | None:
    return user_repository.get_user_by_id(db, user_id)


def login_user(
    db: Session,
    login_data: UserLogin,
) -> dict[str, str | int]:
    email = str(login_data.email).strip().lower()

    user = user_repository.get_user_by_email(db, email)

    if user is None or not verify_password(
        login_data.password,
        user.Password,
    ):
        raise ValueError("Invalid email or password")

    return {
        "message": "Login successful",
        "user_id": user.UserID,
        "name": user.Name,
        "email": user.Email,
    }
