# filename: product/routers/admin_router.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from fastapi import APIRouter, Depends, HTTPException, Path, status
from pydantic import BaseModel, Field, field_validator
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from product.db.session import get_db
from product.models.category import Category
from product.models.product import Product
from product.repositories import (
    category_repository,
    order_repository,
    product_repository,
)
from product.schemas.category_schema import (
    CategoryCreate,
    CategoryResponse,
)
from product.schemas.order_schema import OrderHistoryResponse
from product.schemas.product_schema import (
    ProductCreate,
    ProductResponse,
    ProductUpdate,
)
from product.services import category_service, product_service
from fastapi import APIRouter, Depends

from product.models.user import User
from product.utils.security import require_roles


router = APIRouter(
    prefix="/admin",
    tags=["Admin"],
)


class CategoryUpdate(BaseModel):
    category_name: str = Field(
        ...,
        min_length=1,
        max_length=100,
    )

    @field_validator("category_name")
    @classmethod
    def validate_category_name(cls, value: str) -> str:
        cleaned_value = value.strip()

        if not cleaned_value:
            raise ValueError(
                "Category name cannot be empty"
            )

        return cleaned_value


def convert_value_error(error: ValueError) -> HTTPException:
    message = str(error)
    message_lower = message.lower()

    if "not found" in message_lower:
        error_status = status.HTTP_404_NOT_FOUND
    elif "already exists" in message_lower:
        error_status = status.HTTP_409_CONFLICT
    else:
        error_status = status.HTTP_400_BAD_REQUEST

    return HTTPException(
        status_code=error_status,
        detail=message,
    )


@router.post(
    "/products",
    response_model=ProductResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_roles("admin"))],
)
def create_admin_product(
    product_data: ProductCreate,
    db: Session = Depends(get_db),
):
    try:
        return product_service.create_product(
            db=db,
            product_data=product_data,
        )
    except ValueError as error:
        raise convert_value_error(error) from error
    except IntegrityError as error:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Product name already exists",
        ) from error


@router.get(
    "/products",
    response_model=list[ProductResponse],
    dependencies=[Depends(require_roles("admin"))],
)
def get_admin_products(
    db: Session = Depends(get_db),
):
    return product_service.get_all_products(db)


@router.get(
    "/products/{product_id}",
    response_model=ProductResponse,
    dependencies=[Depends(require_roles("admin"))],
)
def get_admin_product(
    product_id: int = Path(..., gt=0),
    db: Session = Depends(get_db),
):
    product = product_repository.get_product_by_id(
        db=db,
        product_id=product_id,
    )

    if product is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Product not found",
        )

    return product


@router.put(
    "/products/{product_id}",
    response_model=ProductResponse,
    dependencies=[Depends(require_roles("admin"))],
)
def update_admin_product(
    product_data: ProductUpdate,
    product_id: int = Path(..., gt=0),
    db: Session = Depends(get_db),
):
    product = product_repository.get_product_by_id(
        db=db,
        product_id=product_id,
    )

    if product is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Product not found",
        )

    updates = product_data.model_dump(
        exclude_unset=True,
    )

    if "category_id" in updates:
        category = category_repository.get_category_by_id(
            db=db,
            category_id=updates["category_id"],
        )

        if category is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Category not found",
            )

    if "product_name" in updates:
        duplicate_product = (
            db.query(Product)
            .filter(
                Product.ProductName == updates["product_name"],
                Product.ProductID != product_id,
            )
            .first()
        )

        if duplicate_product is not None:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Product name already exists",
            )

    field_mapping = {
        "product_name": "ProductName",
        "description": "Description",
        "category_id": "CategoryID",
        "price": "Price",
        "available_quantity": "AvailableQuantity",
        "product_url": "ProductUrl",
    }

    for schema_field, model_field in field_mapping.items():
        if schema_field not in updates:
            continue

        value = updates[schema_field]

        if schema_field == "product_url" and value is not None:
            value = str(value)

        setattr(product, model_field, value)

    try:
        db.commit()
        db.refresh(product)
        return product
    except IntegrityError as error:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Product update violates a database constraint",
        ) from error


@router.post(
    "/categories",
    response_model=CategoryResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_roles("admin"))],
)
def create_admin_category(
    category_data: CategoryCreate,
    db: Session = Depends(get_db),
):
    try:
        return category_service.create_category(
            db=db,
            category_data=category_data,
        )
    except ValueError as error:
        raise convert_value_error(error) from error
    except IntegrityError as error:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Category already exists",
        ) from error


@router.get(
    "/categories",
    response_model=list[CategoryResponse],
    dependencies=[Depends(require_roles("admin"))],
)
def get_admin_categories(
    db: Session = Depends(get_db),
):
    return category_service.get_all_categories(db)


@router.put(
    "/categories/{category_id}",
    response_model=CategoryResponse,
    dependencies=[Depends(require_roles("admin"))],
)
def update_admin_category(
    category_data: CategoryUpdate,
    category_id: int = Path(..., gt=0),
    db: Session = Depends(get_db),
):
    category = category_repository.get_category_by_id(
        db=db,
        category_id=category_id,
    )

    if category is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Category not found",
        )

    duplicate_category = (
        db.query(Category)
        .filter(
            Category.CategoryName == category_data.category_name,
            Category.CategoryID != category_id,
        )
        .first()
    )

    if duplicate_category is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Category already exists",
        )

    category.CategoryName = category_data.category_name

    try:
        db.commit()
        db.refresh(category)
        return category
    except IntegrityError as error:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Category update violates a database constraint",
        ) from error


@router.get(
    "/orders",
    response_model=list[OrderHistoryResponse],
    dependencies=[Depends(require_roles("admin", "support"))],
)
def get_admin_order_summaries(
    db: Session = Depends(get_db),
):
    return order_repository.get_all_orders(db)
