# filename: product/routers/order_router.py | Code Generated by Sidekick is for learning and experimentation purposes only.

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Path,
    status,
)
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from product.db.session import get_db
from product.models.user import User
from product.schemas.order_schema import (
    OrderCreate,
    OrderHistoryResponse,
    OrderResponse,
)
from product.services import order_service
from product.utils.security import require_roles


router = APIRouter(
    prefix="/orders",
    tags=["Orders"],
)


def service_error_to_http(error: ValueError) -> HTTPException:
    message = str(error)
    message_lower = message.lower()

    if (
        "not found" in message_lower
        or "no longer exists" in message_lower
    ):
        error_status = status.HTTP_404_NOT_FOUND
    elif "stock" in message_lower:
        error_status = status.HTTP_409_CONFLICT
    elif (
        "permission" in message_lower
        or "own" in message_lower
    ):
        error_status = status.HTTP_403_FORBIDDEN
    else:
        error_status = status.HTTP_400_BAD_REQUEST

    return HTTPException(
        status_code=error_status,
        detail=message,
    )


@router.post(
    "/checkout",
    response_model=OrderResponse,
    status_code=status.HTTP_201_CREATED,
)
def checkout(
    order_data: OrderCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_roles("customer"),
    ),
):
    secured_order_data = order_data.model_copy(
        update={
            "user_id": current_user.UserID,
        },
    )

    try:
        return order_service.create_order(
            db=db,
            order_data=secured_order_data,
            user_id=current_user.UserID,
        )

    except ValueError as error:
        raise service_error_to_http(error) from error

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Unable to place the order",
        ) from error


@router.get(
    "/me",
    response_model=list[OrderHistoryResponse],
)
def get_my_orders(
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_roles("customer"),
    ),
):
    try:
        return order_service.get_orders_by_user(
            db=db,
            user_id=current_user.UserID,
        )

    except ValueError as error:
        raise service_error_to_http(error) from error


@router.get(
    "/details/{order_id}",
    response_model=OrderResponse,
)
def get_order_details(
    order_id: int = Path(
        ...,
        gt=0,
    ),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_roles(
            "customer",
            "admin",
            "support",
        ),
    ),
):
    order = order_service.get_order_by_id(
        db=db,
        order_id=order_id,
    )

    if order is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Order not found",
        )

    current_role = (current_user.Role or "").lower()

    if (
        current_role == "customer"
        and order.UserID != current_user.UserID
    ):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can view only your own order details",
        )

    return order


@router.get(
    "/{user_id}",
    response_model=list[OrderHistoryResponse],
)
def get_order_history(
    user_id: int = Path(
        ...,
        gt=0,
    ),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_roles(
            "customer",
            "admin",
            "support",
        ),
    ),
):
    current_role = (current_user.Role or "").lower()

    if (
        current_role == "customer"
        and user_id != current_user.UserID
    ):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You can view only your own orders",
        )

    try:
        return order_service.get_orders_by_user(
            db=db,
            user_id=user_id,
        )

    except ValueError as error:
        raise service_error_to_http(error) from error
