# filename: product/utils/logger.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import json
import logging
from datetime import datetime, timezone


class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        log_entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }

        return json.dumps(log_entry)


logger = logging.getLogger("shopping-api")
logger.setLevel(logging.INFO)
logger.propagate = False

for existing_handler in logger.handlers[:]:
    logger.removeHandler(existing_handler)
    existing_handler.close()

file_handler = logging.FileHandler(
    "app.log",
    encoding="utf-8",
)

file_handler.setFormatter(JsonFormatter())
logger.addHandler(file_handler)
